<a href="https://colab.research.google.com/github/oussama016/ML-camp-journey/blob/main/Intro%20to%20Machine%20Learning/1_7numpy_intro_mlbookcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Machine learning Zoomcamp :
\

# Introduction to NumPy

---



reference 🇰
NumPy Cheat Sheet : https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python

numpy dictionnary website : https://mlbookcamp.com/article/numpy

In [2]:
import numpy as np

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10,)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [29]:
a = np.array([10,2,2,3,6])
a[2] = 20

In [30]:
a[0]

10

In [31]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [32]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Multi dimensiional array 

---



In [51]:
a = np.array([[10,2,2,3,6],[5,6,7,8,9],[5,6,7,8,9]])

In [55]:
a[0,4] = 20
a[0,4]

20

In [66]:
a[0:2,0:2]

array([[10,  2],
       [ 5,  6]])

In [36]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.arange(2,9,2)

array([2, 4, 6, 8])


# Randomly generated arrays 

---





In [78]:
np.random.seed(2)
np.random.rand(5,2)
#between 0 and 100 
100*np.random.rand(5,2)

array([[62.11338328, 52.91420943],
       [13.45799453, 51.35781213],
       [18.44398656, 78.53351478],
       [85.39752926, 49.42368374],
       [84.65614854,  7.9645477 ]])

In [77]:
np.random.seed(2)
np.random.randn(5,2)
#

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [85]:
np.random.randint(low=0, high=100 , size=(10,2))

array([[17, 22],
       [73, 57],
       [90, 62],
       [83, 96],
       [43, 32],
       [26,  8],
       [76, 10],
       [40, 34],
       [60,  9],
       [70, 86]])

#Element wise operations

---



In [87]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [95]:
c = (b*2)/10
c

array([0. , 0.2, 0.4, 0.6, 0.8])

In [90]:
we cannot do the same thing with the normal array / list  , 
a=[1,2,3,4,5,6]
a+1

TypeError: ignored

# **Comparaison** 

In [109]:
c==b
c<b

array([False,  True,  True,  True,  True])

In [108]:
c[c<b]

array([0.2, 0.4, 0.6, 0.8])

# **Summerisation or aggregation** 

In [110]:
b

array([0, 1, 2, 3, 4])

In [111]:
b.sum()

10

In [112]:
b.max()

4

In [115]:
b.mean()

2.0

In [116]:
b.std()

1.4142135623730951