<a href="https://colab.research.google.com/github/oussama016/ML-camp-journey/blob/main/Intro%20to%20Machine%20Learning/1_8Linear_Algebra_intro_mlbookcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vector Operations


---



In [2]:
import numpy as np

In [3]:
# a vector is a column or a row


#*vector*-vector *multiplication*


In [4]:
#dot product
uu = np.array([[10,25,47,96],[10,25,2,5]])
v = np.array([10,25,2,5]) 
uu*v
v.shape[0]

4

In [5]:
def vector_vector_multipli (u,v) :
  assert  u.shape[0] == v.shape[0]
  n= u.shape[0]
  result = 0
  for i in range(n):
    result += u[i]*v[i]
  return result


In [6]:
u = np.array([10,25,47])
v = np.array([10,25,2]) 
vector_vector_multipli (u,v)

819

In [7]:
u.dot(v)

819

# Matrix vector multiplication

In [32]:
U = np.array([[1,2,3],[2,5,8],[1,2,3]])
U.shape[1]
U[0,:]

array([1, 2, 3])

In [9]:
v= np.array([5,9,1])
v.shape[0]


3

In [10]:
def Matrix_vector_multipli (U,v) :
  assert U.shape[1]==v.shape[0]
  num_rows = U.shape[0]
  result = np.zeros(num_rows)
  for i in range(num_rows):
    result[i] = vector_vector_multipli (U[i,:],v)
    
  return result

Matrix_vector_multipli (U,v)




array([26., 63., 26.])

In [11]:
U.dot(v)

array([26, 63, 26])

# Matrix matrix multiplication 

In [36]:
U = np.array([[1,2,3,7],[2,5,8,7],[1,2,3,9]])
U.shape

(3, 4)

In [38]:
V = np.array([[11,2,43],[21,50,8],[12,2,63],[2,5,8]])
V

array([[11,  2, 43],
       [21, 50,  8],
       [12,  2, 63],
       [ 2,  5,  8]])

In [23]:
#result=np.zeros((4,3))
#result

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
def matrix_matrix_multiplication (U,V):
    assert U.shape[1]==V.shape[0]
    # V colomns determines the colomns of u*v and U rows determines the rows u*v 
    result=np.zeros((U.shape[0],V.shape[1]))
    for i in range(V.shape[1]):
      x=V[:,i]
      y =  Matrix_vector_multipli (U,x)
      result[:,i] = y

    return result
matrix_matrix_multiplication(U,V)

array([[103., 143., 304.],
       [237., 305., 686.],
       [107., 153., 320.]])

In [40]:
U.dot(V)

array([[103, 143, 304],
       [237, 305, 686],
       [107, 153, 320]])

# Identity matrix

In [52]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
V.dot(I)

array([[11.,  2., 43.],
       [21., 50.,  8.],
       [12.,  2., 63.],
       [ 2.,  5.,  8.]])

In [54]:
matrix_matrix_multiplication(V,I)

array([[11.,  2., 43.],
       [21., 50.,  8.],
       [12.,  2., 63.],
       [ 2.,  5.,  8.]])

# Inverse MATRIX

In [72]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [73]:
#square matrix is in which size columns = size rows
vsquare = V[:3,:]
vsquare

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [74]:
Vinverse = np.linalg.inv(vsquare)
Vinverse

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [75]:
#A INVERSE * A c est la matrice identite
Vinverse.dot(vsquare)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])