<a href="https://colab.research.google.com/github/oussama016/ML-camp-journey/blob/main/Intro%20to%20Machine%20Learning/test01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# the Car price dataset with the questions are below the code section



# code section

In [120]:
import numpy as np
import pandas as pd

import io
import requests


In [121]:
url = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"

In [122]:
s=requests.get(url).content

In [123]:
c=pd.read_csv(io.StringIO(s.decode('utf-8')))
c.head(3)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350

In [124]:
#How many records are in the dataset?
c.describe().round()

Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
count  11914.0    11845.0           11884.0          11908.0      11914.0   
mean    2010.0      249.0               6.0              3.0         27.0   
std        8.0      109.0               2.0              1.0          9.0   
min     1990.0       55.0               0.0              2.0         12.0   
25%     2007.0      170.0               4.0              2.0         22.0   
50%     2015.0      227.0               6.0              4.0         26.0   
75%     2016.0      300.0               6.0              4.0         30.0   
max     2017.0     1001.0              16.0              4.0        354.0   

       city mpg  Popularity       MSRP  
count   11914.0     11914.0    11914.0  
mean       20.0      1555.0    40595.0  
std         9.0      1442.0    60109.0  
min         7.0         2.0     2000.0  
25%        16.0       549.0    21000.0  
50%        18.0      1385.0    29995.0  
75%        22.0      2009.0    42231.0  
max       137.0      5657.0  2065902.0

In [125]:
#How many records are in the dataset?
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [126]:
#correction of How many records are in the dataset?
c.shape[0]

11914

In [127]:
df = c.copy()

In [128]:
#Who are the most frequent car manufacturers (top-3) according to the dataset?
df.groupby('Make').MSRP.count().nlargest(3)

Make
Chevrolet     1123
Ford           881
Volkswagen     809
Name: MSRP, dtype: int64

In [129]:
#correction of #Who are the most frequent car manufacturers (top-3) according to the dataset?
df['Make'].value_counts().head()

Chevrolet     1123
Ford           881
Volkswagen     809
Toyota         746
Dodge          626
Name: Make, dtype: int64

In [130]:
#What's the number of unique Audi car models in the dataset?
df[df['Make'] == 'Audi'].Model.unique()

array(['100', '200', '80', '90', 'A3', 'A4 allroad', 'A4', 'A5', 'A6',
       'A7', 'A8', 'allroad quattro', 'allroad', 'Cabriolet', 'Coupe',
       'Q3', 'Q5', 'Q7', 'R8', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'SQ5', 'TT RS', 'TT', 'TTS', 'V8'],
      dtype=object)

In [131]:
df[df['Make'] == 'Audi'].Model.nunique()

34

In [132]:
#How many columns in the dataset have missing values?
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [133]:
#Correction How many columns in the dataset have missing values?
(df.isnull().sum()!= 0).sum()


5

In [134]:
#Find the median value of "Engine Cylinders" column in the dataset.
df["Engine Cylinders"].median(),df["Engine Cylinders"].mean(),df["Engine Cylinders"].mode()

(6.0, 5.628828677213059, 0    4.0
 dtype: float64)

In [135]:
#calculate the most frequent value of the same "Engine Cylinders".
df.nlargest(4,"Engine Cylinders")

Make        Model  Year             Engine Fuel Type  Engine HP  \
11362  Bugatti  Veyron 16.4  2008  premium unleaded (required)     1001.0   
11363  Bugatti  Veyron 16.4  2008  premium unleaded (required)     1001.0   
11364  Bugatti  Veyron 16.4  2009  premium unleaded (required)     1001.0   
460    Ferrari         456M  2001  premium unleaded (required)      442.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
11362              16.0  AUTOMATED_MANUAL   all wheel drive              2.0   
11363              16.0  AUTOMATED_MANUAL   all wheel drive              2.0   
11364              16.0  AUTOMATED_MANUAL   all wheel drive              2.0   
460                12.0         AUTOMATIC  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
11362  Exotic,High-Performance      Compact         Coupe           14   
11363  Exotic,High-Performance      Compact         Coupe           14   
11364  Exotic,High-Performance      Compact         Coupe           14   
460    Exotic,High-Performance      Compact         Coupe           14   

       city mpg  Popularity     MSRP  
11362         8         820  2065902  
11363         8         820  1500000  
11364         8         820  1705769  
460           9        2774   223970

In [136]:
df["Engine Cylinders"].describe()
df["Engine Cylinders"].unique()

array([ 6.,  4.,  5.,  8., 12.,  0., nan, 10.,  3., 16.])

In [137]:
df["Engine Cylinders"].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [138]:

#calculate percentage 11914 is lenght from df.shape() = (11914, 16)
df["Engine Cylinders"].value_counts()/11914*100


4.0     39.885849
6.0     37.678362
8.0     17.047171
12.0     1.930502
5.0      1.888534
10.0     0.570757
0.0      0.470035
3.0      0.251805
16.0     0.025180
Name: Engine Cylinders, dtype: float64

*Use* the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step


In [139]:
#@title Titre par défaut
#Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step


In [140]:
#calculate the number of null
df["Engine Cylinders"].isnull().sum()

30

In [141]:
#with 4.0 cylinders having     39.885849% we will replace it with the null values

In [142]:
df["Engine Cylinders"] = df["Engine Cylinders"].fillna(4)

In [143]:
#test the null values after filling
df["Engine Cylinders"].isnull().sum()

0

In [144]:
#Now, calculate the median value of "Engine Cylinders" once again.
df["Engine Cylinders"].median(),df["Engine Cylinders"].mean(),df["Engine Cylinders"].mode()
#nope it did not change

(6.0, 5.624727211683734, 0    4.0
 dtype: float64)


    Select all the "Lotus" cars from the dataset.
    Select all the "Lotus" cars from the dataset.
    Select only columns "Engine HP", "Engine Cylinders".
    Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
    Get the underlying NumPy array. Let's call it X.
    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    Compute the inverse of XTX.
    Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    What's the value of the first element of w?


In [145]:
#Select all the "Lotus" cars from the dataset.
#df.Make.unique()
dfq7 = df[df["Make"] == "Lotus"].copy()


#Select only columns "Engine HP", "Engine Cylinders"
dfq7_3 = dfq7 [[ "Engine HP", "Engine Cylinders"]]

In [146]:
#number of dupliactes except the first occurence
dfq7_3.duplicated().sum()

20

In [147]:
dfq7_3.drop_duplicates(inplace=True)
dfq7_3.duplicated().sum()

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


0

In [148]:
dfq7_3.count()

Engine HP           9
Engine Cylinders    9
dtype: int64

In [149]:
#Get the underlying NumPy array. Let's call it X.
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
X = np.array(dfq7_3)
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [150]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [155]:
XTX = X.dot(X.T)
XTX

array([[ 35737.,  41218.,  41029.,  66182.,  75624.,  52188.,  65229.,
         48589.,  45376.],
       [ 41218.,  47540.,  47322.,  76332.,  87224.,  60192.,  75234.,
         56042.,  52336.],
       [ 41029.,  47322.,  47105.,  75982.,  86824.,  59916.,  74889.,
         55785.,  52096.],
       [ 66182.,  76332.,  75982., 122564., 140048.,  96648., 120798.,
         89982.,  84032.],
       [ 75624.,  87224.,  86824., 140048., 160036., 110436., 138036.,
        102824.,  96024.],
       [ 52188.,  60192.,  59916.,  96648., 110436.,  76212.,  95256.,
         70956.,  66264.],
       [ 65229.,  75234.,  74889., 120798., 138036.,  95256., 119061.,
         88689.,  82824.],
       [ 48589.,  56042.,  55785.,  89982., 102824.,  70956.,  88689.,
         66065.,  61696.],
       [ 45376.,  52336.,  52096.,  84032.,  96024.,  66264.,  82824.,
         61696.,  57616.]])

In [153]:
y= np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [162]:
# Correction *********************************************

#np.linalg.inv(XTX)
#The @ operator, available since Python 3.5, can be used for conventional matrix multiplication
XTX2 = X.T @ X
XTX2inv = np.linalg.inv(XTX2)
w = (XTX2inv @ X.T) @ y
w

array([  4.59494481, -63.56432501])

In [163]:

w[0]


4.594944810094551